---
title: "Lab 03 - Nobel laureates"
author: "Steph Bossert"
date: "06 Feb 21"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
view(nobel)
```

## Exercises

### Exercise 1

```{r}
names(nobel)
glimpse(nobel)
view(nobel)
```

##Exercise 1 answers:
observations: 26 columns x 935 entries = 24310
Variables: 26 variables
Each variable represents demogrpahic information about the nobel laurete 


### Exercise 2

```{r}
nobel_living <- nobel %>%
filter(is.na(died_date), (gender != "org"), (!is.na(country)))
view(nobel_living)

library(tidyverse)
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```

### Exercise 3

```{r}
ggplot(data = nobel_living_science, aes(x= category, fill=country_us)) +
  geom_bar(stat = "count", position = position_dodge()) +
  coord_flip()

```

### Exercise 4

```{r}
nobel_living_science <- nobel_living_science %>%
  mutate(
    born_country_us = if_else(born_country == "USA", "USA", "Other")
  )
view(nobel_living_science)
table(nobel_living_science$born_country_us)
  ###Answer: 147 born in the US
```
### Exercise 5

```{r}
###create new vars for four conditions 
nobel_living_science<- nobel_living_science%>% 
  mutate(Demographics = case_when(born_country_us == "USA" & country_us == "USA" ~ "Born & Won in USA", #condition 1
                         born_country_us == "USA" & country_us == "Other" ~ "Born in USA, Won in Other Country", #condition 2
                         born_country_us == "Other" & country_us == "Other" ~ "Born & Won in Other Country", #condition 3
                         born_country_us == "Other" & country_us == "USA" ~ "Born in Other Country, Won in USA")) #condition 4
view(nobel_living_science)
ggplot(data = nobel_living_science)+ aes(x= category, fill= Demographics) +
  geom_bar(stat = "count", position = position_dodge())
```

### Exercise 6

```{R}
nobel_new<- filter(nobel_living_science, country_us == "USA", born_country_original != "USA")
view(nobel_new)
table(nobel_new$born_country_original)
count(nobel_new, 'born_country_original')

###Answer: 45 people won their prize in the US but were born outside the US. The Uk has the most amount of winners (7) born there but who won their prize in the US. 
```




